config/routes.rb
require 'sidekiq/web'

Migrationrocket::Application.routes.draw do

  resources :users
  
  
  
  # Clients
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  resources :clients
  match "/zendesk/test" => 'clients#zendesk'
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  
  
  
  # Profiles
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  resources :profiles
  match "/imports" => 'profiles#index'
  match "/imports/:id" => 'profiles#show'
  match "/imports/:profile_id/select" => 'profiles#select'
  match "/imports/:profile_id/skip" => 'profiles#skip'
  match "/imports/:profile_id/prev" => 'profiles#prev'
  match "/new_import" => 'profiles#new'
  match "/imports/:id/delete" => 'profiles#destroy'
  match "/imports/:profile_id/rollback" => 'profiles#rollback'
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  
  
  
  # Mapping
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  resources :mapping,path: "/imports/:profile_id/mapping/:type"
  match "/imports/:profile_id/mapping/:type/:map_id/deactivate" => 'mapping#deactivate'
  match "/imports/:profile_id/mapping/:type/:map_id/activate" => 'mapping#activate'
  #match "/imports/:profile_id/mapping/new" => 'mapping#new'
  #match "/imports/:profile_id/mapping/create" => 'mapping#create'
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  
  
  
  # Import
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  resources :import
  match "/imports/:profile_id/import/:type" => 'import#index'
  match "/imports/:profile_id/import/:type/status" => 'import#status'
  match "/imports/:profile_id/import/:type/start" => 'import#start'
  match "/imports/:profile_id/import/:type/stop" => 'import#stop'
  match "/imports/:profile_id/import/:type/reset" => 'import#reset'
  match "/imports/:profile_id/import/:type/log" => 'import#log'
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  
  
  
  # Sync
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  resources :sync
  match "/imports/:profile_id/sync" => 'sync#index'
  match "/imports/:profile_id/sync/start" => 'sync#start'
  match "/imports/:profile_id/sync/status" => 'sync#status'
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  
  
  
  # CSV
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  resources :csv
  match "/imports/:profile_id/csv/:type" => 'csv#files'
  match "/imports/:profile_id/csv/:type/upload" => 'csv#upload'
  match "/imports/:profile_id/csv/:type/attachments/:attachment_id/reset" => 'csv#reset'
  match "/imports/:profile_id/csv/:type/attachments/:attachment_id/log" => 'csv#log'
  match "/imports/:profile_id/csv/:type/attachments/:attachment_id/extract" => 'csv#extract'
  match "/imports/:profile_id/csv/:type/attachments/:attachment_id/raw" => 'csv#raw'
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  
  
  
  # Attachments
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  resources :attachments
  resources :keys
  match "/imports/:profile_id/csv/:type/attachments/:id/status" => 'attachments#status'
  match "/imports/:profile_id/csv/:type/attachments/:attachment_id/delete" => 'attachments#destroy'
  match "/imports/:profile_id/csv/:type/attachments/:id/status" => 'attachments#status'
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  
  
  
  # Desk
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  resources :desk,path: "/desk"
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  
  
  
  resources :sessions  
  get 'sessions/new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'access/login', to: 'sessions#new', as: 'login'
  get 'access/logout', to: 'sessions#destroy', as: 'logout'
  
  root :to => 'profiles#splash'
  
  mount Sidekiq::Web, at: '/sidekiq'
  #mount Sidekiq::Web, at: "/sidekiq"
  
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :active, :complete, :file, :locked, :open, :profile_id, :state, :status, :total
  validates_presence_of :file
  mount_uploader :file,FileUploader
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  
  before_filter :authorize
  
  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attachments }
    end
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/new
  # GET /attachments/new.json
  def new
    @attachment = Attachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/1/edit
  def edit
    @attachment = Attachment.find(params[:id])
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(params[:attachment])

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render json: @attachment, status: :created, location: @attachment }
      else
        format.html { render action: "new" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attachments/1
  # PUT /attachments/1.json
  def update
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      if @attachment.update_attributes(params[:attachment])
        format.html { head :no_content }
        format.json { head :no_content }
      else
        format.html { head :no_content }
        format.json { head :no_content }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    
    @attachment = Attachment.find(params[:attachment_id])
    @attachment.destroy
    Keys.where(attachment_id: @attachment.id).destroy_all
    GetModel(params[:type]).where(file_id: @attachment.id).destroy_all
    
    respond_to do |format|      
      format.html { redirect_to '/imports/'+params[:profile_id].to_s+'/csv/'+params[:type].to_s,notice: 'File has been deleted!' }
    end
    
  end
  
  
  def status
    
    @attachment = Attachment.find(params[:id])
    
    final = {
      clean: true,
      status: @attachment.status,
      success: GetModel(params[:type]).where("file_id = #{params[:id]}").count,
      errors: CsvErrors.where("file_id = #{params[:id]}").count,
      complete: @attachment.complete,
      total: @attachment.total,
      pct: ((@attachment.complete.to_f/@attachment.total.to_f)*100.to_f).round
    }
    
    respond_to do |format|      
      format.json { render json: final }    
    end
    
  end
  
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= form_for(@attachment) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_id %><br />
    <%= f.number_field :profile_id %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :file %><br />
    <%= f.text_field :file %>
  </div>
  <div class="field">
    <%= f.label :open %><br />
    <%= f.check_box :open %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :complete %><br />
    <%= f.number_field :complete %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.number_field :total %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :locked %><br />
    <%= f.check_box :locked %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<h1>Listing attachments</h1>

<table>
  <tr>
    <th>Profile</th>
    <th>State</th>
    <th>File</th>
    <th>Open</th>
    <th>Status</th>
    <th>Complete</th>
    <th>Total</th>
    <th>Active</th>
    <th>Locked</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attachments.each do |attachment| %>
  <tr>
    <td><%= attachment.profile_id %></td>
    <td><%= attachment.state %></td>
    <td><%= attachment.file %></td>
    <td><%= attachment.open %></td>
    <td><%= attachment.status %></td>
    <td><%= attachment.complete %></td>
    <td><%= attachment.total %></td>
    <td><%= attachment.active %></td>
    <td><%= attachment.locked %></td>
    <td><%= link_to 'Show', attachment %></td>
    <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
    <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Profile:</b>
  <%= @attachment.profile_id %>
</p>

<p>
  <b>State:</b>
  <%= @attachment.state %>
</p>

<p>
  <b>File:</b>
  <%= @attachment.file %>
</p>

<p>
  <b>Open:</b>
  <%= @attachment.open %>
</p>

<p>
  <b>Status:</b>
  <%= @attachment.status %>
</p>

<p>
  <b>Complete:</b>
  <%= @attachment.complete %>
</p>

<p>
  <b>Total:</b>
  <%= @attachment.total %>
</p>

<p>
  <b>Active:</b>
  <%= @attachment.active %>
</p>

<p>
  <b>Locked:</b>
  <%= @attachment.locked %>
</p>


<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>